version: "3.0"
services:
  mono:
    image: mono:6.12
    container_name: mono_container
    ports:
    - "8080:8080"
    volumes:
    - /home/damon/Documents/USASK/4thYear/winter/cmpt436/assignments/A2:/usr/src/app
    working_dir: /usr/src/app
    stdin_open: true
    tty: true
  java:
    image: openjdk:11
    container_name: java_container
    ports:
    - "8081:8081"
    volumes:
    - /home/damon/Documents/USASK/4thYear/winter/cmpt436/assignments/A2:/usr/src/app
    working_dir: /usr/src/app
    command:
      - /bin/bash
    stdin_open: true
    tty: true